In [1]:
from instagram_private_api import Client, ClientCompatPatch
from instagram.client import InstagramAPI
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import instaloader
import time
import random

In [2]:
L = instaloader.Instaloader()
user_name = 'partyherdapp'
password = 'AUX-IN-01-partyherd'
L.login(user_name, password)        # (login)
api = Client(user_name, password)
results = api.feed_timeline()
items = [item for item in results.get('feed_items', [])
         if item.get('media_or_ad')]
# for item in items:
#     ClientCompatPatch.media(item['media_or_ad'])
#     print(item['media_or_ad']['code'])

In [3]:

####DUMPPPPP
# x = api.user_recent_media(427553890, 1)
# # api.media_comments(media_id)
# # api.create_media_comment(media_id, text)
# print(api.search_users("apoorv_singh12").keys())
# #CHECK USING A GIVEN USERNAME
# print(api.search_users("leomessi")["users"][0])
# print(api.top_search("#quarantine")["hashtags"][1])
# for i in range(len(api.user_feed(427553890)['items'][0]['carousel_media'])):
# xxx = api.generate_uuid(return_hex=False)
# doc = api.user_followers(427553890, rank_token=xxx)['users']
# for d in range(len(doc)):
#     print(d, doc[d]['username'])
# doc = api.user_following(427553890, rank_token=xxx)['users']
# for d in range(len(doc)):
#     print(d, doc[d]['username'])
####################################################
# profile = instaloader.Profile.from_username(L.context, "dragon.ball.id")
# count=0
# file = open("my_followers.txt","a+")
# for followee in profile.get_followers():
#     username = followee.username
#     print(count, username)
#     count+=1
#     file.write(username + "\n")
#     if(count == 500):
#         time.sleep(random.randint(300,360))
# file.close()

# Required Functions

In [3]:
def funclike(username,count):
    tmp = 0
    profile = instaloader.Profile.from_username(L.context, username)
    allposts = profile.get_posts()
    for post in allposts:
        if tmp >=2:
            break
        try:
            api.post_like(post.mediaid)
            count+=1
            tmp+=1
            print("post ",tmp)
        except:
            print("error")
            continue
    return count
def retrieve_last_seen_id(file_name):
    f_read = open(file_name, 'r')
    last_seen_id = f_read.readlines()
    f_read.close()
    return last_seen_id
def store_last_seen_id(last_seen_id, file_name):
    f_write = open(file_name, 'a')
    f_write.write(last_seen_id)
    f_write.write('\n')
    f_write.close()
    return

# Getting the Follower List

In [ ]:
profile = instaloader.Profile.from_username(L.context, "houseconcertindia")
count=0
file = open("my_followers.txt","a+")
for followee in profile.get_followers():
    username = followee.username
    print(count, username)
    count+=1
    file.write(username + "\n")
    if(count == 500):
        time.sleep(random.randint(300,360))
file.close()

# Commenting on the Followers

In [4]:
# profile = instaloader.Profile.from_username(L.context, "apoorv_singh12")
follow_list = []
count=0
totcount=0
# file1 = open("my_followers_1.txt","a+")
idd = retrieve_last_seen_id("my_followers.txt")
for idx in range(len(idd)):
    username = idd[idx][:-1]
    if(count >200):
        break
    try:
        boool = instaloader.Profile.from_username(L.context, username).is_private
    except:
        print("acc doesnt exist")
        boool = True
    if(boool == False):
        print(count, username)
        count = funclike(username,count)
        time.sleep(random.randint(20,25))
    else:
        print(username, " is private")
        time.sleep(random.randint(20,25))
    totcount+=1
# file.close()
follow_list = idd[totcount:]
open('my_followers.txt', 'w').close()
f = open('my_followers.txt', 'w')
for i in range(len(follow_list)):
    f.write(follow_list[i][:-1] + "\n")
f.close()

0 sriram_v2
post  1
post  2
2 ayanjoemusic
post  1
post  2
4 artistiklicense
post  1
post  2
6 man_a_f
post  1
post  2
8 houseconcertchennai
post  1
post  2
10 houseconcertbombay
post  1
post  2
12 houseconcertpune
post  1
post  2
14 houseconcertbangalore
post  1
post  2
16 houseconcertchandigarh
post  1
post  2
18 houseconcertsdelhi
post  1
post  2
20 its_a.nil
post  1
post  2
rajesiddhesh95  is private
22 houseconcertgoa
post  1
post  2
24 thisfrontier
post  1
post  2
26 snehalsharma
post  1
post  2


# READING THE INSTA PROFILE

In [1]:
# importing the module 
import json 
  
# Opening JSON file 
with open('samay.json') as json_file: 
    data = json.load(json_file) 
##THE PAGE
data.keys()

dict_keys(['logging_page_id', 'show_suggested_profiles', 'show_follow_dialog', 'graphql', 'toast_content_on_load'])

In [2]:
##ALL INFO ABOUT USER
data['graphql']['user'].keys()

dict_keys(['biography', 'blocked_by_viewer', 'restricted_by_viewer', 'country_block', 'external_url', 'external_url_linkshimmed', 'edge_followed_by', 'followed_by_viewer', 'edge_follow', 'follows_viewer', 'full_name', 'has_ar_effects', 'has_guides', 'has_channel', 'has_blocked_viewer', 'highlight_reel_count', 'has_requested_viewer', 'id', 'is_business_account', 'is_joined_recently', 'business_category_name', 'overall_category_name', 'category_enum', 'is_private', 'is_verified', 'edge_mutual_followed_by', 'profile_pic_url', 'profile_pic_url_hd', 'requested_by_viewer', 'username', 'connected_fb_page', 'edge_felix_video_timeline', 'edge_owner_to_timeline_media', 'edge_saved_media', 'edge_media_collections'])

In [3]:
###ALL INFO ABOUT MEDIA
data['graphql']['user']['edge_owner_to_timeline_media'].keys()

dict_keys(['count', 'page_info', 'edges'])

In [4]:
data['graphql']['user']['edge_owner_to_timeline_media']['page_info']

{'has_next_page': True,
 'end_cursor': 'QVFBR3VSQlNCNlh3Vkp0T2czWnd2Qi05V3ZhaWRqZmdmWEdwQ3NQSzFvcGZMRWduZkNpeFFESm1WYXd0ZFlEcWVmb0ZhZkE2SEoycHpvb1poLXBtUm1YUw=='}

In [5]:
###FIRST POST
data['graphql']['user']['edge_owner_to_timeline_media']['edges'][6]['node']
# data['graphql']['user']['edge_owner_to_timeline_media']['edges'][3]['node']['edge_media_to_caption']['edges'][0]['node']['text']

{'__typename': 'GraphVideo',
 'id': '2352916532076427403',
 'shortcode': 'CCnPR6gjziL',
 'dimensions': {'height': 750, 'width': 750},
 'display_url': 'https://scontent-bom1-2.cdninstagram.com/v/t51.2885-15/e35/108470186_185231066337776_6199943375259826728_n.jpg?_nc_ht=scontent-bom1-2.cdninstagram.com&_nc_cat=108&_nc_ohc=z8IEsp_BylYAX_FF6aP&oh=69c87eb330ff713acfc7a373c0da3c3c&oe=5F2B6792',
 'gating_info': None,
 'fact_check_overall_rating': None,
 'fact_check_information': None,
 'media_overlay_info': None,
 'media_preview': 'ACoqsBaYybzj86lHJ4pspwMDvWyjzavfojNy5TONrJcANuwOy9gO34+tNktjbAMDuBOCKux7xwCMY446fWlZWdcPgng8dKw5mne52OCcbNFRlHrTdq+tTMR6UYHpSk3N+70FC1Ne91LhkHQVVnuFiGXPJ6Duap3VyYjtX7x/SstmLHJ5Ndzajotzy1B1fek7R7I24G84BhwT2ouGKxtsJBXnP41Dpcg5T3z+dTiRpGeN8Zxg+p7ZrkSvI9Jy90yxdydzn8Kf9tk9vyqqwwcHtTa1StsZPXcu6hHtcN6j+VUK1tSHA/3v6Vk1CldXBq2hraYACZO47eg9aIyQ+9ucsf1PJPtj8Ko27ESLg4zxVnPzv9QPzIzVpWdx30sRXa7ZD6HmqtaOodV/H+lZ1Mk//9k=',
 'owner': {'id': '541673116', 'username': 'maisamayhoon'},

In [7]:
#STORE ALL THE COMMENTS
doc = ""
i=0
for post in data['graphql']['user']['edge_owner_to_timeline_media']['edges']:
    try:
        print(i,post['node']['edge_media_to_caption']['edges'][0]['node']['text'])
        doc+= (post['node']['edge_media_to_caption']['edges'][0]['node']['text'])
        doc+=" "
    except:
        print(i,"no comment")
    i+=1

0 Happy Friendship Day
1 Found an essay I had written 16 years ago. Sweet memories ♥️
2 Caption this
3 Check out my new JBL Club Series headphones with True Adaptive Noise Cancelling and JBL Legendary Pro Sound. It's engineered with world-class technology so that nothing comes between you and your music. Not even your neighbour. #JBL #DareToListen #WhereYourMusicAt #TuneInNoiseOut #ClubSeries #JBLLegendaryProSound
4 Smiling but dead inside
5 Thanks for this @thethugarmy

@taniasachdev @viditchess @anishgiri94 @randomvarun @rahulsubramanic @tanmaybhat @karansinghmagic @missbotez
6 no comment
7 Don't you worry, don't you worry child, heaven's got no plan for youuu
8 Thank you for #arrestshubhammishra
9 Flex
10 Although online dating has become a norm, that first conversation is still a nightmare to pull off. You want to come across as a good listener, but how many questions are too many? Or till when is it still early to ask her for her number? And how are emojis going to make me look? W

In [9]:
doc
words = []
texts_2 = [text for text in doc.split(' ')]

In [10]:
texts_2

['Happy',
 'Friendship',
 'Day',
 'Found',
 'an',
 'essay',
 'I',
 'had',
 'written',
 '16',
 'years',
 'ago.',
 'Sweet',
 'memories',
 '♥️',
 'Caption',
 'this',
 'Check',
 'out',
 'my',
 'new',
 'JBL',
 'Club',
 'Series',
 'headphones',
 'with',
 'True',
 'Adaptive',
 'Noise',
 'Cancelling',
 'and',
 'JBL',
 'Legendary',
 'Pro',
 'Sound.',
 "It's",
 'engineered',
 'with',
 'world-class',
 'technology',
 'so',
 'that',
 'nothing',
 'comes',
 'between',
 'you',
 'and',
 'your',
 'music.',
 'Not',
 'even',
 'your',
 'neighbour.',
 '#JBL',
 '#DareToListen',
 '#WhereYourMusicAt',
 '#TuneInNoiseOut',
 '#ClubSeries',
 '#JBLLegendaryProSound',
 'Smiling',
 'but',
 'dead',
 'inside',
 'Thanks',
 'for',
 'this',
 '@thethugarmy\n\n@taniasachdev',
 '@viditchess',
 '@anishgiri94',
 '@randomvarun',
 '@rahulsubramanic',
 '@tanmaybhat',
 '@karansinghmagic',
 '@missbotez',
 "Don't",
 'you',
 'worry,',
 "don't",
 'you',
 'worry',
 'child,',
 "heaven's",
 'got',
 'no',
 'plan',
 'for',
 'youuu',
 'Than

In [ ]:
# importing the module 
import json 
  
# Opening JSON file 
with open('samaytmp.json') as json_file: 
    data = json.load(json_file) 
##THE PAGE
data.keys()

In [ ]:
# i=0
# for post in data['graphql']['hashtag']['edge_hashtag_to_media']['edges']:
#     try:
#         print(i,post['node']['edge_media_to_caption']['edges'][0]['node']['text'])
#     except:
#         print(i,"no comment")
#     i+=1
# # data['graphql']['hashtag']['edge_hashtag_to_media']['edges'][1]['node']['edge_media_to_caption']['edges'][0]['node']['text']

In [ ]:
i=0
for post in data['graphql']['user']['edge_owner_to_timeline_media']['edges']:
    try:
        print(i,post['node']['edge_media_to_caption']['edges'][0]['node']['text'])
    except:
        print(i,"no comment")
    i+=1

In [ ]:
data['graphql']['user'].keys()

In [ ]:
data['graphql']['user']['edge_owner_to_timeline_media']

# Reading the Glove Text File

In [5]:

import numpy as np
from scipy import spatial
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

In [6]:
embeddings_dict = {}
with open("glove.6B.50d.txt", 'r') as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], "float32")
        embeddings_dict[word] = vector

In [7]:
def find_closest_embeddings(embedding):
    return sorted(embeddings_dict.keys(), key=lambda word: spatial.distance.euclidean(embeddings_dict[word], embedding))

In [8]:
print(find_closest_embeddings(embeddings_dict["king"])[1:6])

['prince', 'queen', 'uncle', 'ii', 'grandson']


In [6]:
print(find_closest_embeddings(embeddings_dict["king"] - embeddings_dict["man"] + embeddings_dict["woman"]
)[:5])

['king', 'queen', 'prince', 'elizabeth', 'daughter']


In [9]:
embeddings_dict['friend']

array([ 0.1669   ,  0.98757  , -0.027122 , -0.29075  ,  1.1917   ,
        0.56752  , -1.2344   ,  0.51221  , -0.69893  , -0.011795 ,
       -0.16918  ,  1.0709   , -0.53755  , -0.10829  ,  0.77406  ,
       -0.29525  , -0.23824  ,  0.26055  ,  0.2545   ,  0.0072983,
       -0.11534  ,  1.2641   , -0.059262 ,  0.27406  ,  0.7965   ,
       -2.1522   , -0.15152  , -0.3725   ,  0.068102 , -0.24862  ,
        1.6662   , -0.36509  , -0.24184  , -0.17983  ,  0.09604  ,
        0.083266 , -0.3055   ,  0.29688  ,  0.43182  , -0.53256  ,
        0.41804  ,  0.88657  , -0.64102  , -0.4662   ,  0.75824  ,
       -0.54164  , -0.5663   , -1.1662   , -0.014035 ,  0.76166  ],
      dtype=float32)

In [10]:
embeddings_dict['hello']

array([-0.38497 ,  0.80092 ,  0.064106, -0.28355 , -0.026759, -0.34532 ,
       -0.64253 , -0.11729 , -0.33257 ,  0.55243 , -0.087813,  0.9035  ,
        0.47102 ,  0.56657 ,  0.6985  , -0.35229 , -0.86542 ,  0.90573 ,
        0.03576 , -0.071705, -0.12327 ,  0.54923 ,  0.47005 ,  0.35572 ,
        1.2611  , -0.67581 , -0.94983 ,  0.68666 ,  0.3871  , -1.3492  ,
        0.63512 ,  0.46416 , -0.48814 ,  0.83827 , -0.9246  , -0.33722 ,
        0.53741 , -1.0616  , -0.081403, -0.67111 ,  0.30923 , -0.3923  ,
       -0.55002 , -0.68827 ,  0.58049 , -0.11626 ,  0.013139, -0.57654 ,
        0.048833,  0.67204 ], dtype=float32)

In [11]:
embeddings_dict['and']

array([ 0.26818 ,  0.14346 , -0.27877 ,  0.016257,  0.11384 ,  0.69923 ,
       -0.51332 , -0.47368 , -0.33075 , -0.13834 ,  0.2702  ,  0.30938 ,
       -0.45012 , -0.4127  , -0.09932 ,  0.038085,  0.029749,  0.10076 ,
       -0.25058 , -0.51818 ,  0.34558 ,  0.44922 ,  0.48791 , -0.080866,
       -0.10121 , -1.3777  , -0.10866 , -0.23201 ,  0.012839, -0.46508 ,
        3.8463  ,  0.31362 ,  0.13643 , -0.52244 ,  0.3302  ,  0.33707 ,
       -0.35601 ,  0.32431 ,  0.12041 ,  0.3512  , -0.069043,  0.36885 ,
        0.25168 , -0.24517 ,  0.25381 ,  0.1367  , -0.31178 , -0.6321  ,
       -0.25028 , -0.38097 ], dtype=float32)